/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdjusterDashboardDto } from '../../models/adjuster-dashboard-dto';

export interface ApiUsersDashboardGet$Json$Params {
}

export function apiUsersDashboardGet$Json(http: HttpClient, rootUrl: string, params?: ApiUsersDashboardGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<AdjusterDashboardDto>> {
  const rb = new RequestBuilder(rootUrl, apiUsersDashboardGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdjusterDashboardDto>;
    })
  );
}

apiUsersDashboardGet$Json.PATH = '/api/Users/dashboard';
