/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateReadStatusRequest } from '../../models/update-read-status-request';

export interface ApiCommunicationsCommIdReadStatusPut$Json$Params {
  commId: string;
      body: UpdateReadStatusRequest
}

export function apiCommunicationsCommIdReadStatusPut$Json(http: HttpClient, rootUrl: string, params: ApiCommunicationsCommIdReadStatusPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, apiCommunicationsCommIdReadStatusPut$Json.PATH, 'put');
  if (params) {
    rb.path('commId', params.commId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

apiCommunicationsCommIdReadStatusPut$Json.PATH = '/api/Communications/{commId}/read-status';
