/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiCommunicationsChannelsGet$Plain$Params {
}

export function apiCommunicationsChannelsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiCommunicationsChannelsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: boolean;
}>> {
  const rb = new RequestBuilder(rootUrl, apiCommunicationsChannelsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: boolean;
      }>;
    })
  );
}

apiCommunicationsChannelsGet$Plain.PATH = '/api/Communications/channels';
