/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommunicationThreadDto } from '../../models/communication-thread-dto';

export interface ApiCommunicationsClaimClaimIdPartyPartyIdGet$Plain$Params {
  claimId: (number | string);
  partyId: (number | string);
}

export function apiCommunicationsClaimClaimIdPartyPartyIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiCommunicationsClaimClaimIdPartyPartyIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CommunicationThreadDto>> {
  const rb = new RequestBuilder(rootUrl, apiCommunicationsClaimClaimIdPartyPartyIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('claimId', params.claimId, {});
    rb.path('partyId', params.partyId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommunicationThreadDto>;
    })
  );
}

apiCommunicationsClaimClaimIdPartyPartyIdGet$Plain.PATH = '/api/Communications/claim/{claimId}/party/{partyId}';
