/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnreadCommunicationDto } from '../../models/unread-communication-dto';

export interface ApiCommunicationsUnreadGet$Json$Params {
}

export function apiCommunicationsUnreadGet$Json(http: HttpClient, rootUrl: string, params?: ApiCommunicationsUnreadGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UnreadCommunicationDto>>> {
  const rb = new RequestBuilder(rootUrl, apiCommunicationsUnreadGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UnreadCommunicationDto>>;
    })
  );
}

apiCommunicationsUnreadGet$Json.PATH = '/api/Communications/unread';
