/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateNotesRequest } from '../../models/update-notes-request';

export interface ApiCommunicationsCommIdNotesPut$Plain$Params {
  commId: string;
      body: UpdateNotesRequest
}

export function apiCommunicationsCommIdNotesPut$Plain(http: HttpClient, rootUrl: string, params: ApiCommunicationsCommIdNotesPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, apiCommunicationsCommIdNotesPut$Plain.PATH, 'put');
  if (params) {
    rb.path('commId', params.commId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

apiCommunicationsCommIdNotesPut$Plain.PATH = '/api/Communications/{commId}/notes';
