/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiWebhooksSmsReceivePost$Params {
      body: {
'MessageSid'?: string;
'SmsSid'?: string;
'AccountSid'?: string;
'MessagingServiceSid'?: string;
'From'?: string;
'To'?: string;
'Body'?: string;
'NumMedia'?: (number | string);
}
}

export function apiWebhooksSmsReceivePost(http: HttpClient, rootUrl: string, params: ApiWebhooksSmsReceivePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiWebhooksSmsReceivePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiWebhooksSmsReceivePost.PATH = '/api/webhooks/sms/receive';
