/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvolvedPartyDto } from '../../models/involved-party-dto';

export interface ApiClaimsClaimIdPartiesGet$Plain$Params {
  claimId: (number | string);
}

export function apiClaimsClaimIdPartiesGet$Plain(http: HttpClient, rootUrl: string, params: ApiClaimsClaimIdPartiesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InvolvedPartyDto>>> {
  const rb = new RequestBuilder(rootUrl, apiClaimsClaimIdPartiesGet$Plain.PATH, 'get');
  if (params) {
    rb.path('claimId', params.claimId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InvolvedPartyDto>>;
    })
  );
}

apiClaimsClaimIdPartiesGet$Plain.PATH = '/api/Claims/{claimId}/parties';
