/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClaimDetailsDto } from '../../models/claim-details-dto';

export interface ApiClaimsClaimIdGet$Plain$Params {
  claimId: (number | string);
}

export function apiClaimsClaimIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiClaimsClaimIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ClaimDetailsDto>> {
  const rb = new RequestBuilder(rootUrl, apiClaimsClaimIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('claimId', params.claimId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClaimDetailsDto>;
    })
  );
}

apiClaimsClaimIdGet$Plain.PATH = '/api/Claims/{claimId}';
