/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignedClaimDto } from '../../models/assigned-claim-dto';

export interface ApiClaimsAssignedToAdjusterGet$Json$Params {
}

export function apiClaimsAssignedToAdjusterGet$Json(http: HttpClient, rootUrl: string, params?: ApiClaimsAssignedToAdjusterGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AssignedClaimDto>>> {
  const rb = new RequestBuilder(rootUrl, apiClaimsAssignedToAdjusterGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AssignedClaimDto>>;
    })
  );
}

apiClaimsAssignedToAdjusterGet$Json.PATH = '/api/Claims/assigned-to-adjuster';
