/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssignedClaimDto } from '../models/assigned-claim-dto';
export interface AdjusterDashboardDto {
  adjusterId?: (number | string);
  adjusterName?: (string | null);
  assignedClaims?: (Array<AssignedClaimDto> | null);
  email?: (string | null);
  isActive?: boolean;
  unreadCommunicationCount?: (number | string);
}
