/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdjusterDto {
  adjusterId?: (number | string);
  email?: (string | null);
  fullName?: (string | null);
  isActive?: (boolean | null);
  phone?: (string | null);
}
