/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignedClaimDto {
  claimFiledOn?: (string | null);
  claimId?: (number | string);
  claimNumber?: (string | null);
  policyNumber?: (string | null);
  status?: (string | null);
  unreadCommunicationCount?: (number | string);
}
