/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AttachmentDto {
  attachmentId?: string;
  fileName?: (string | null);
  fileSize?: (number | string | null);
  fileUrl?: (string | null);
  mimeType?: (string | null);
}
