/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdjusterDto } from '../models/adjuster-dto';
export interface AuthResponse {
  message?: (string | null);
  success?: boolean;
  token?: (string | null);
  user?: (null | AdjusterDto);
}
