/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InvolvedPartyDto } from '../models/involved-party-dto';
export interface ClaimDetailsDto {
  claimClosedOn?: (string | null);
  claimFiledOn?: (string | null);
  claimId?: (number | string);
  claimNumber?: (string | null);
  involvedParties?: (Array<InvolvedPartyDto> | null);
  isAdjusterActive?: boolean;
  assignedAdjusterName?: (string | null);
  policyNumber?: (string | null);
  status?: (string | null);
}
