/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvolvedPartyDto {
  email?: (string | null);
  firstName?: (string | null);
  fullName?: (string | null);
  involvedPartyType?: (string | null);
  isActive?: (boolean | null);
  lastName?: (string | null);
  partyId?: (number | string);
  phone?: (string | null);
  isInjured?: (boolean | null);
}
