/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendEmailRequest {
  body: string;
  claimId: (number | string);
  partyId: (number | string);
  subject: string;
  to: string;
}
