/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendCommunicationRequest {
  attachmentIds?: (Array<string> | null);
  attachmentUrls?: (Array<string> | null);
  body?: (string | null);
  cc?: (string | null);
  claimId?: (number | string);
  mode?: (string | null);
  partyId?: (number | string);
  signature?: (string | null);
  subject?: (string | null);
  to?: (string | null);
}
