/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SendSmsRequest {
  claimId: (number | string);
  message: string;
  partyId: (number | string);
  phoneNumber: string;
}
