/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignupRequest {
  confirmPassword?: string;
  email?: string;
  fullName?: string;
  password?: string;
  phone?: (string | null);
}
