/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
import { AttachmentDto } from './attachment-dto';

export interface UnreadCommunicationDto {
  attachments?: (Array<AttachmentDto> | null);
  claimId?: (number | string);
  claimNumber?: (string | null);
  communicationId?: string;
  communicationMode?: (string | null);
  isRead?: (boolean | null);
  messagePreview?: (string | null);
  partyId?: (number | string);
  policyNumber?: (string | null);
  receivedAt?: (string | null);
  senderName?: (string | null);
  status?: (string | null);
}
